spring.application.name=myApp


#DB configuration
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}


server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# JWT configuration
jwt.secret=ChangeThisSecretKeyForJWTGeneration123456789
jwt.expiration-ms=86400000

spring.config.import=optional:application-secret.properties,optional:application-local.properties